force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerTriggerHelperSOQLGovenorLimitFix.cls
public class CustomerTriggerHelperSOQLGovenorLimitFix 
{

    public static void isAfterUpdateCall(List<Customer__c> customerList, 
    Map<id, Customer__c> oldMapCustomer, Map<id, Customer__c> newMapCustomer) 
    {
        createInvoiceReocrds(customerList, oldMapCustomer);
        updateInvoiceDesc(customerList, newMapCustomer);
    }
    
    public static void createInvoiceReocrds(List<Customer__c> customerList,
    Map<id, Customer__c>oldMapCustomer) 
    {
        List<Invoice__c> invoiceList = new List<Invoice__c>();
        for (Customer__c objCustomer:customerList) 
        {
            if (objCustomer.Customer_Status__c == 'Active' 
            && oldMapCustomer.get(objCustomer.id).Customer_Status__c == 'Inactive') 
            {
                Invoice__c objInvoice = new Invoice__c();
                objInvoice.Status__c = 'Pending';
                objInvoice.Customer__c = objCustomer.id;
                InvoiceList.add(objInvoice);
            }
        }
        insert invoiceList;
    }
    
    public static void updateInvoiceDesc(List<Customer__c> customerList, Map<id, Customer__c> newMapCustomer) 
    {
        List<Customer__c> customerListWithInvoice = [select id, name, (select id, name, description__c from Invoices__r) from Customer__c where Id IN:newMapCustomer.keySet()];
      
        List<Invoice__c> invoiceToUpdate = new List<Invoice__c>();
        List<Invoice__c> invoiceList = customerListWithInvoice[0].Invoices__r;
        for (Invoice__c objInv:invoiceList )
        {
            objInv.Description__c = 'OK To Pay';
            invoiceToUpdate.add(objInv);
        }
        update invoiceToUpdate;
    
    }
}